apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-ingress
  annotations:
    kubernetes.io/ingress.class: nginx # Specifies the Ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: / # Optional: Rewrites all paths to the root
spec:
  rules:
    - host: your-domain.com # Replace with your actual domain name
      http:
        paths:
          - path: /
            pathType: Prefix # Matches all paths starting with /
            backend:
              service:
                name: angular-web-app-service
                port:
                  number: 80
