apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-iam-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14 # Or your preferred version
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: <your_db_user> # Replace with your database user
        - name: POSTGRES_PASSWORD
          value: <your_db_password> # Replace with your database password (INSECURE!)
        - name: POSTGRES_DB
          value: <your_db_name> # Replace with your database name
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc # See PersistentVolumeClaim below